const errorCodes = {
  EMAIL_NOT_VALID: 'EMAIL_NOT_VALID',
  EMAIL_ALREADY_IN_USE: 'EMAIL_ALREADY_IN_USE',
  PASSWORD_INVALID: 'PASSWORD_INVALID',
  PASSWORD_INVALID_LENGTH: 'PASSWORD_INVALID_LENGTH',
  PASSWORD_NOT_VALID: 'PASSWORD_NOT_VALID',
  POST_AUTHOR_INVALID: 'POST_AUTHOR_INVALID',
  USER_NOT_EXISTS: 'USER_NOT_EXISTS',
  POST_TITLE_INVALID: 'POST_TITLE_INVALID',
  POST_TITLE_INVALID_LENGTH: 'POST_TITLE_INVALID_LENGTH',
  POST_BODY_INVALID: 'POST_BODY_INVALID',
  POST_BODY_INVALID_LENGTH: 'POST_BODY_INVALID_LENGTH',
  POST_NOT_EXISTS: 'POST_NOT_EXISTS',
  ID_INVALID: 'ID_INVALID',
  LANGUAGE_NOT_VALID: 'LANGUAGE_NOT_VALID',
  POST_USER_LOGGEDIN_DIFFERENT_FROM_THE_AUTHOR:
    'POST_USER_LOGGEDIN_DIFFERENT_FROM_THE_AUTHOR',
  POST_AUTHOR_NOT_FOUND: 'POST_AUTHOR_NOT_FOUND',
  POST_COMMENT_INVALID: 'POST_COMMENT_INVALID',
};

export default errorCodes;
